Services
marksadykov/spaceOfSpace pull request #4
Opened 2021-04-04 17:57 UTC by Dellvin

2021-04-04 18:19 UTC, iamfrommoscow requested changes

2021-04-04 18:19 UTC, iamfrommoscow commented on spaceOfSpace/spaceOfSpace/Scenes/Services/ArPlanet/Elements/conf.swift
> +    var RadiusRatio:Float
давай всё же не называть свойства и методы классов большими буквами. Знаю, что в го так можно и нужно, но в го нет статичных/нестатичных свойств и методов (как и классов). Здесь же со временем будешь сам путаться и путать своих коллег по проекту

2021-04-04 18:19 UTC, iamfrommoscow commented on spaceOfSpace/spaceOfSpace/Scenes/Services/ArPlanet/ServicesArPlanetController.swift
> +    var router: (NSObjectProtocol & ServicesArPlanetRoutingLogic & ServicesArPlanetDataPassing)?
Вообще несколько странно видеть здесь NSObjectProtocol

2021-04-04 18:19 UTC, iamfrommoscow commented on spaceOfSpace/spaceOfSpace/Scenes/Services/ArPlanet/ServicesArPlanetController.swift
> +    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
если ты пишешь вёрстку кодом, такой инит тебе не нужен

2021-04-04 18:19 UTC, iamfrommoscow commented on spaceOfSpace/spaceOfSpace/Scenes/Services/Elements/ServicesTable.swift
> +        switch indexPath.row {
эта логика должна быть в презентере, но это мы ещё обсудим

2021-04-04 18:19 UTC, iamfrommoscow commented on spaceOfSpace/spaceOfSpace/Scenes/Services/ArPlanet/Elements/Planet.swift
> +        let sphere=planet.geometry as! SCNSphere
force cast-ы - это зло

2021-04-04 18:19 UTC, iamfrommoscow commented on spaceOfSpace/spaceOfSpace/Scenes/Services/ArPlanet/Elements/SceneController.swift
> +        let distance = simd_distance((sys.Solar.first?.planet.simdTransform.columns.3)!, (ViewController.sceneView.session.currentFrame?.camera.transform.columns.3)!);
force unwrap-ы - это тоже зло

2021-04-05 08:11 UTC, Dellvin commented on spaceOfSpace/spaceOfSpace/Scenes/Services/ArPlanet/Elements/conf.swift
> +    var RadiusRatio:Float
Окей, просто в го (самое дебильно решение евер) если переменная должна быть видна в других файлах она должна быть с большой, если нет то с маленькой

2021-04-05 08:12 UTC, Dellvin commented on spaceOfSpace/spaceOfSpace/Scenes/Services/ArPlanet/ServicesArPlanetController.swift
> +    var router: (NSObjectProtocol & ServicesArPlanetRoutingLogic & ServicesArPlanetDataPassing)?
эт не мое, эт кирилл так нагенерил

2021-04-05 08:12 UTC, Dellvin commented on spaceOfSpace/spaceOfSpace/Scenes/Services/ArPlanet/ServicesArPlanetController.swift
> +    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
ок

2021-04-05 08:13 UTC, Dellvin commented on spaceOfSpace/spaceOfSpace/Scenes/Services/Elements/ServicesTable.swift
> +        switch indexPath.row {
с нетерпением жду обсуждения, пушто не хочу больше писать код как обезьяна)

2021-04-11 20:22 UTC, closed without merging